#:kivy 1.7.1
<SayThis>:
    orientation: 'vertical'
    Label:
        text: 'Say This!'
        size_hint: 1, None
    TextInput:
        text: 'Hello, world!'
    Slider:
        orientation: 'horizontal'
        size_hint: 1, None
    BoxLayout:
        orientation: 'horizontal'
        size_hint: 1, None
        Button:
            text: 'Say it!'
            size_hint: 1, None
        Button:
            text: 'Clear'
            size_hint: 1, None
